services:
  inaccel-vadd:
    depends_on:
      init:
        condition: service_completed_successfully
    image: inaccel/vadd
    volumes:
    - volume:/var/lib/inaccel
  init:
    command:
    - bitstream
    - install
    - https://store.inaccel.com/artifactory/bitstreams/intel/pac_s10/9346116da52d5ca8b06aa9a389ef7c8d//vector/1/1addition
    image: inaccel/cli
    volumes:
    - volume:/var/lib/inaccel
volumes:
  volume:
    driver: inaccel
