apiVersion: v1
kind: Pod
metadata:
  annotations:
    inaccel/cli: |
      bitstream install https://store.inaccel.com/artifactory/bitstreams/intel/pac_s10/9346116da52d5ca8b06aa9a389ef7c8d//vector/1/1addition
  labels:
    inaccel/fpga: enabled
  name: inaccel-vadd
spec:
  containers:
  - image: inaccel/vadd
    name: inaccel-vadd
    resources:
      limits:
        intel/pac_s10: 1
  nodeSelector:
    intel/pac_s10: 9346116da52d5ca8b06aa9a389ef7c8d
  restartPolicy: Never
