apiVersion: v1
kind: Pod
metadata:
  name: inaccel-vadd
spec:
  containers:
  - image: inaccel/vadd
    name: inaccel-vadd
    resources:
      limits:
        ${VENDOR}/${NAME}: 1
    volumeMounts:
    - mountPath: /var/lib/inaccel
      name: inaccel
  initContainers:
  - args:
    - bitstream
    - install
    - https://store.inaccel.com/artifactory/bitstreams/${VENDOR}/${NAME}/${VERSION}/${LABELS}/vector/1/1addition
    image: inaccel/cli
    name: init
    volumeMounts:
    - mountPath: /var/lib/inaccel
      name: inaccel
  nodeSelector:
    ${VENDOR}/${NAME}: ${VERSION}
  restartPolicy: OnFailure
  volumes:
  - csi:
      driver: inaccel
    name: inaccel
