services:
  inaccel-vadd:
    depends_on:
      init:
        condition: service_completed_successfully
    image: inaccel/vadd
    volumes:
    - volume:/var/lib/inaccel
  init:
    command:
    - bitstream
    - install
    - https://store.inaccel.com/artifactory/bitstreams/intel/pac_a10/38d782e3b6125343b9342433e348ac4c//vector/1/1addition
    image: inaccel/cli
    volumes:
    - volume:/var/lib/inaccel
volumes:
  volume:
    driver: inaccel
