apiVersion: v1
kind: Pod
metadata:
  annotations:
    inaccel/cli: |
      bitstream install https://store.inaccel.com/artifactory/bitstreams/xilinx/u280/gen3x16_xdma_base.1//vector/1/1addition
  labels:
    inaccel/fpga: enabled
  name: inaccel-vadd
spec:
  containers:
  - image: inaccel/vadd
    name: inaccel-vadd
    resources:
      limits:
        xilinx/u280: 1
  nodeSelector:
    xilinx/u280: gen3x16_xdma_base.1
  restartPolicy: Never
