services:
  inaccel-vadd:
    depends_on:
      init:
        condition: service_completed_successfully
    image: inaccel/vadd
    volumes:
    - volume:/var/lib/inaccel
  init:
    command:
    - bitstream
    - install
    - https://store.inaccel.com/artifactory/bitstreams/intel/ofs_ia420fr0/06dd1e32478657c38c353dc048cdb7e0//vector/1/1addition
    image: inaccel/cli
    volumes:
    - volume:/var/lib/inaccel
volumes:
  volume:
    driver: inaccel
