name: dockerhub
on: workflow_dispatch
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - run: echo GITHUB_SHORT_SHA=${GITHUB_SHA:0:7} >> ${GITHUB_ENV}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          inaccel/vadd:latest
          inaccel/vadd:${{ env.GITHUB_SHORT_SHA }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## Docker images

          - `docker pull inaccel/vadd:${{ env.GITHUB_SHORT_SHA }}`
        tag_name: ${{ env.GITHUB_SHORT_SHA }}
