name: gh-pages
on:
  push:
    paths:
    - deploy/*
    - scripts/deploy.sh
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deployment configurations and templates
      shell: bash
      run: scripts/deploy.sh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        cname: vadd.inaccel.com
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force_orphan: true
        full_commit_message: ${{ github.event.head_commit.id }}
